variable "name_prefix" {
  description = "Resource name prefix."
  type        = string
}

variable "recovery_window_in_days" {
  description = "Secrets Manager recovery window."
  type        = number
  default     = 7
}

variable "tags" {
  description = "Additional tags."
  type        = map(string)
  default     = {}
}

variable "database_url" {
  description = "Optional DATABASE_URL value to store (generated by RDS module)."
  type        = string
  default     = null
  sensitive   = true
}

variable "moderation_operator_token" {
  description = "Optional moderation operator token (set outside git)."
  type        = string
  default     = null
  sensitive   = true
}

variable "sentry_dsn" {
  description = "Optional Sentry DSN."
  type        = string
  default     = null
  sensitive   = true
}

variable "alert_webhook_url" {
  description = "Optional alert webhook URL."
  type        = string
  default     = null
  sensitive   = true
}
